const menuData = [

  {
    id: 1,
    title: "Focaccia",
    category: "breakfast",
    price: 3.00,
    desc: "sale, origano, olio",
  },
  {
    id: 2,
    title: "Focaccia con lardo",
    category: "breakfast",
    price: 5.00,
    desc: "sale, origano, olio, lardo",
  },
  {
    id: 3,
    title: "Focaccia con crudo",
    category: "breakfast",
    price: 5.50,
    desc: "sale, origano, olio, prosciutto crudo",
  },
  {
    id: 4,
    title: "Focaccia con nutella",
    category: "breakfast",
    price: 5.00,
    desc: "focaccia con nutella",
  },
  {
    id: 5,
    title: "Focaccia capri",
    category: "breakfast",
    price: 9.50,
    desc: "pomodorini, mozzarella di bufala, crudo, rucola",
  },
  {
    id: 6,
    title: "Marinara",
    category: "breakfast",
    price: 4.50,
    desc: "pomodoro, olio, aglio, origano",
  },
  {
    id: 7,
    title: "Margherita",
    category: "breakfast",
    price: 5.50,
    desc: "pomodoro, mozzarella fior di latte",
  },
  {
    id: 8,
    title: "Wurstel",
    category: "breakfast",
    price: 6.50,
    desc: "pomodoro, mozzarella fior di latte, wurstel",
  },
  {
    id: 9,
    title: "Diavola",
    category: "breakfast",
    price: 6.50,
    desc: "pomodoro, mozzarella fior di latte, salame piccante",
  },
  {
    id: 10,
    title: "Prosciutto",
    category: "breakfast",
    price: 6.50,
    desc: "pomodoro, mozzarella fior di latte, prosciutto cotto",
  },
  {
    id: 11,
    title: "Napoli",
    category: "breakfast",
    price: 6.50,
    desc: "pomodoro, mozzarella fior di latte, acciughe",
  },
  {
    id: 12,
    title: "Prosciutto e funghi",
    category: "breakfast",
    price: 7.50,
    desc: "pomodoro, mozzarella fior di latte, prosciutto, funghi",
  },
  {
    id: 13,
    title: "Quattro stagioni",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, prosciutto, funghi, carciofi, olive",
  },
  {
    id: 14,
    title: "Capricciosa",
    category: "breakfast",
    price: 9.50,
    desc: "pomodoro, mozzarella fior di latte, cotto, funghi, carciofi, olive, acciughe, origano",
  },
  {
    id: 15,
    title: "Calzone liscio",
    category: "breakfast",
    price: 7.00,
    desc: "pomodoro, mozzarella fior di latte, prosciutto cotto",
  },
  {
    id: 16,
    title: "Calzone farcito",
    category: "breakfast",
    price: 8.00,
    desc: "pomodoro, mozzarella fior di latte, cotto, carciofi, olive, funghi",
  },
  {
    id: 17,
    title: "Tonno",
    category: "breakfast",
    price: 8.00,
    desc: "pomodoro, mozzarella fior di latte, tonno",
  },
  {
    id: 18,
    title: "Tonno e cipolle",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, tonno, cipolle",
  },
  {
    id: 19,
    title: "Ortolana",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, zucchine, melanzane, peperoni",
  },
  {
    id: 20,
    title: "Parmigiano",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, melanzane, grana, olio ex.",
  },
  {
    id: 21,
    title: "Speck e brie",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, speck, brie",
  },
  {
    id: 22,
    title: "Affumicata",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, scamorza affumicata, speck",
  },
  {
    id: 23,
    title: "Quattro formaggi",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, gorgonzola, taleggio, grana",
  },
  {
    id: 24,
    title: "Porcini",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, funghi porcini",
  },
  {
    id: 25,
    title: "Rustica",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, salame piccante, cipolla, gorgonzola",
  },
  {
    id: 26,
    title: "Bufala",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella di bufala, basilico, olio ex",
  },
  {
    id: 27,
    title: "Corsara",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, salame piccante, capperi, acciughe, olive piccanti, origano",
  },
  {
    id: 28,
    title: "Bismarck",
    category: "breakfast",
    price: 8.00,
    desc: "pomodoro, mozzarella fior di latte, prosciutto cotto, uovo",
  },
  {
    id: 29,
    title: "Golosa",
    category: "breakfast",
    price: 9.50,
    desc: "pomodoro, mozzarella fior di latte, salsiccia, wurstel, salame piccante, cipolla, peperoni, origano",
  },
  {
    id: 30,
    title: "Del pizzaiolo",
    category: "breakfast",
    price: 9.50,
    desc: "pomodoro, mozzarella fior di latte, crudo, rucola, grana",
  },
  {
    id: 31,
    title: "Speciale",
    category: "breakfast",
    price: 10.00,
    desc: "pomodoro, pomodorini, mozzarella fior di latte, mozzarella di bufala, crudo, porcini",
  },
  {
    id: 32,
    title: "Frutti di mare",
    category: "breakfast",
    price: 9.00,
    desc: "pomodoro, mozzarella fior di latte, frutti di mare*, prezzemolo",
  },
  {
    id: 33,
    title: "Bomba",
    category: "breakfast",
    price: 9.50,
    desc: "pomodoro, mozzarella fior di latte, wurstel, salame piccante, uovo, salsiccia, olive piccanti",
  },
  {
    id: 34,
    title: "Patatine",
    category: "breakfast",
    price: 7.50,
    desc: "pomodoro, mozzarella fior di latte, patatine*",
  },
  {
    id: 35,
    title: "Americana",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, wurstel, patatine*",
  },
  {
    id: 36,
    title: "Calabrisella",
    category: "breakfast",
    price: 8.50,
    desc: "pomodoro, mozzarella fior di latte, salame piccante, olive piccanti, cipolla, salsiccia, origano",
  },
  {
    id: 37,
    title: "Romana",
    category: "breakfast",
    price: 7.50,
    desc: "pomodoro, mozzarella fior di latte, olive nere, capperi, acciughe, origano",
  },
  {
    id: 38,
    title: "Valtellinese",
    category: "breakfast",
    price: 9.50,
    desc: "pomodoro, mozzarella fior di latte, bresaola, rucola, grana, olio ex",
  },
  {
    id: 39,
    title: "Gamberetti e rucola",
    category: "breakfast",
    price: 9.00,
    desc: "pomodoro, mozzarella fior di latte, gamberetti, rucola",
  },
  {
    id: 40,
    title: "Porcini speck",
    category: "breakfast",
    price: 9.50,
    desc: "mozzarella fior di latte, porcini, speck",
  },
  {
    id: 41,
    title: "Sorrentina",
    category: "breakfast",
    price: 7.50,
    desc: "mozzarella fior di latte, pomodorini, rucola, grana",
  },
  {
    id: 42,
    title: "Scamorza e trevisana",
    category: "breakfast",
    price: 7.50,
    desc: "mozzarella fior di latte, scamorza, trevisana",
  },
  {
    id: 43,
    title: "Taleggio",
    category: "breakfast",
    price: 7.50,
    desc: "mozzarella fior di latte, taleggio, zucchine",
  },
  {
    id: 110,
    title: "Cheese bacon burger",
    category: "lunch",
    price: 10.00,
    desc: "hamburger 200g, bacon, maionese, cheddar",
  },
  {
    id: 111,
    title: "629 Burger",
    category: "lunch",
    price: 11.00,
    desc: "hamburger 200g, bacon, maionese, cheddar, insalata, pomodoro",
  },
  {
    id: 112,
    title: "Cheese burger",
    category: "lunch",
    price: 10.00,
    desc: "hamburger 200g, doppio cheddar",
  },
  {
    id: 113,
    title: "BBQ burger",
    category: "lunch",
    price: 11.00,
    desc: "hamburger 200g, insalata, pomodoro, cipolla caramellata, salsa barbecue",
  },
  {
    id: 114,
    title: "West burger",
    category: "lunch",
    price: 12.00,
    desc: "hamburger 200g, insalata, cheddar, anelli di cipolla fritti e bacon, maionese",
  },
  {
    id: 115,
    title: "Chicken burger",
    category: "lunch",
    price: 11.00,
    desc: "hamburger di pollo impanato 200g, insalata, pomodoro, salsa dressing",
  },
  {
    id: 116,
    title: "Chili cheese burger",
    category: "lunch",
    price: 12.00,
    desc: "hamburger 200g, insalata, pomodoro, cheddar, cipolla fresca e peperoncino",
  },
  {
    id: 117,
    title: "Tirolo burger",
    category: "lunch",
    price: 12.00,
    desc: "hamburger 200g, scamorza, speck, insalata, pomodoro, cipolla caramellata",
  },
  {
    id: 118,
    title: "Hot Dog con patatine",
    category: "lunch",
    price: 6.00,
    desc: "",
  },
  {
    id: 98,
    title: "Jalapenos ripieni con formaggio (4 pz)",
    category: "finger",
    price: 5.00,
    desc: "",
  },
  {
    id: 99,
    title: "Spicy potatoes",
    category: "finger",
    price: 5.00,
    desc: "spicchi di patate con buccia leggermente speziati",
  },
  {
    id: 100,
    title: "Nachos con salsa piccante",
    category: "finger",
    price: 4.00,
    desc: "",
  },
  {
    id: 101,
    title: "Nachos con guacamole",
    category: "finger",
    price: 5.00,
    desc: "",
  },
  {
    id: 102,
    title: "Nachos tipicos",
    category: "finger",
    price: 5.50,
    desc: "",
  },
  {
    id: 103,
    title: "Patatine fritte",
    category: "finger",
    price: 4.00,
    desc: "",
  },
  {
    id: 104,
    title: "Guacamole bites",
    category: "finger",
    price: 5.00,
    desc: "Croccantissimo appetizer ripieno di cremoso guacamole",
  },
  {
    id: 105,
    title: "Bastoncini di mozzarella fritti (6 pz)",
    category: "finger",
    price: 5.00,
    desc: "",
  },
  {
    id: 106,
    title: "Anelli di cipolla fritti (10 pz)",
    category: "finger",
    price: 5.00,
    desc: "",
  },
  {
    id: 107,
    title: "Alette di pollo piccanti (4 pz)",
    category: "finger",
    price: 5.00,
    desc: "",
  },
  {
    id: 108,
    title: "Chicken fillet nuggets (6 pz)",
    category: "finger",
    price: 5.50,
    desc: "",
  },
  {
    id: 109,
    title: "Tezer cheese olè",
    category: "finger",
    price: 5.00,
    desc: "Sfiziosissime mini crocchette di patate, con cuore di formaggio cheddar",
  },
  {
    id: 200,
    title: "Mega fab",
    category: "shakes",
    price: 5.50,
    desc: "torta cioccolato",
  },
  {
    id: 201,
    title: "Cheese cake",
    category: "shakes",
    price: 5.00,
    desc: "",
  },
  {
    id: 202,
    title: "Berry Skyr Slices (Gluten Free)",
    category: "shakes",
    price: 5.00,
    desc: "Impasto di mandorle ripieno di formaggio fresco Skyr",
  },
  {
    id: 203,
    title: "Torroncino",
    category: "shakes",
    price: 5.00,
    desc: "",
  },
  {
    id: 204,
    title: "Tartufo bianco",
    category: "shakes",
    price: 5.00,
    desc: "",
  },
  {
    id: 205,
    title: "Tartufo nero",
    category: "shakes",
    price: 5.00,
    desc: "",
  },
  {
    id: 206,
    title: "Cocco ripieni di gelato",
    category: "shakes",
    price: 6.00,
    desc: "",
  },
  {
    id: 207,
    title: "Limone ripieno di gelato",
    category: "shakes",
    price: 6.00,
    desc: "",
  },
  {
    id: 208,
    title: "Croccante al pistacchio",
    category: "shakes",
    price: 5.50,
    desc: "semifreddo con crema al pistacchio",
  },
  {
    id: 209,
    title: "Coppa tiramisù",
    category: "shakes",
    price: 5.00,
    desc: "",
  },
  {
    id: 210,
    title: "Crema catalana",
    category: "shakes",
    price: 6.50,
    desc: "",
  },
  {
    id: 211,
    title: "Coppa profiterol",
    category: "shakes",
    price: 5.00,
    desc: "",
  },
  {
    id: 211,
    title: "Coca cola",
    category: "drink",
    price: 5.00,
    desc: "",
  },


];

export default menuData;
